# Generated by Django 5.0.7 on 2024-08-09 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coffee_name', models.CharField(max_length=256)),
                ('image', models.ImageField(upload_to='coffees/')),
                ('price', models.CharField(max_length=4)),
            ],
            options={
                'verbose_name': 'Coffee',
                'verbose_name_plural': 'Coffees',
            },
        ),
        migrations.CreateModel(
            name='CroissantsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('croissant_name', models.CharField(max_length=256)),
                ('image', models.ImageField(upload_to='croissants/')),
                ('price', models.CharField(max_length=4)),
            ],
            options={
                'verbose_name': 'Croissant',
                'verbose_name_plural': 'Croissants',
            },
        ),
        migrations.CreateModel(
            name='OurMenuModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('our_menu_name', models.CharField(max_length=256)),
                ('coffe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.coffeesmodel')),
                ('croissant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.croissantsmodel')),
            ],
            options={
                'verbose_name': 'Our menu',
                'verbose_name_plural': 'Ours menus',
            },
        ),
    ]
