# Generated by Django 5.0.7 on 2024-08-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeesmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='croissantsmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
